#!/usr/bin/env ruby

class CommandLineNotes

  Color1  = "\e[37m"
  Color2  = "\e[32m"
  NoColor = "\e[0m"

  class Binary
    attr_accessor :notes, :argv
    def initialize(notes, argv)
      self.notes, self.argv = notes, argv
    end

    def call
      if argv == ['-h'] || argv == ['--help']
        @stdout = help_screen
      else
        @stdout = map_with_index(notes_to_print) { |note, note_index|
                    format_note note, note_index
                  }.join("\n") << NoColor
      end
    end

    def stdout
      call
      @stdout
    end

    private

    def help_screen
      "Usage: #{$0} [filters]\n"\
      "\n"\
      "#{notes.description}"
    end

    def notes_to_print
      @notes_to_print ||= notes.notes.
                                select { |values|
                                 filters.all? { |filter|
                                   values.any? { |value| value =~ filter }
                                  }
                                }
    end

    def format_note(note, note_index)
      key         = note[0]
      value       = note[1]
      map_with_index(value.each_line) { |value_line, line_index|
        if line_index.zero?
          "#{note_index % 2== 0 ? Color1 : Color2}#{key.ljust offset_to_value}  #{value_line.chomp}"
        else
          "#{' '*offset_to_value}  #{value_line.chomp}"
        end
      }.join("\n")
    end

    def offset_to_value
      @offset ||= notes_to_print.map(&:first).max_by(&:size).size
    end

    def filters
      @filters ||= argv.map { |arg| Regexp.new arg, Regexp::IGNORECASE }
    end

    # 1.8 doesn't have .with_index
    def map_with_index(collection, &block)
      index = -1
      collection.map do |element|
        index += 1
        block.call element, index
      end
    end
  end

  attr_accessor :description, :notes

  def initialize
    @notes = []
    yield self
  end

  def note(key, value, *tags)
    leading_whitespace = value[/\A */]
    value = value.gsub(/^#{leading_whitespace}/, '')
    notes << [key, value, *tags]
  end
end


if $0 =~ /rspec/
  describe CommandLineNotes do
    def bin(notes, argv)
      CommandLineNotes::Binary.new notes, argv
    end

    it 'prints the description if you give it -h' do
      notes = CommandLineNotes.new { |cln| cln.description = 'mah description' }
      bin(notes, ['-h']).stdout.should include 'mah description'
      bin(notes, ['--help']).stdout.should include 'mah description'
    end

    it 'prints all notes by default' do
      notes = CommandLineNotes.new do |cln|
        cln.note 'key1', 'value1'
        cln.note 'key2', 'value2'
      end
      bin(notes, []).stdout.should include 'key1'
      bin(notes, []).stdout.should include 'key2'
    end

    it 'selects notes whose key matches when given an arg' do
      notes = CommandLineNotes.new do |cln|
        cln.note 'key1', 'value1'
        cln.note 'key2', 'value2'
      end
      bin(notes, ['key1']).stdout.should include 'key1'
    end

    it 'selects notes whose value matches when given an arg' do
      notes = CommandLineNotes.new do |cln|
        cln.note 'key1', 'value1'
        cln.note 'key2', 'value2'
      end
      bin(notes, ['value1']).stdout.should include 'key1'
    end

    it 'selects notes whose tags match when given an arg' do
      notes = CommandLineNotes.new do |cln|
        cln.note 'key1', 'value1', 'tag1'
        cln.note 'key2', 'value2', 'tag2'
      end
      bin(notes, ['tag1']).stdout.should include 'key1'
    end

    it 'treats multiple arguments as successive filters' do
      notes = CommandLineNotes.new do |cln|
        cln.note 'key1', 'value1', 'tag1'
        cln.note 'key2', 'value2', 'tag1', 'tag2'
      end
      bin(notes, ['tag1', 'tag2']).stdout.should_not include 'key1'
      bin(notes, ['tag1', 'tag2']).stdout.should include 'key2'
    end

    it 'does not print the tags' do
      notes = CommandLineNotes.new do |cln|
        cln.note 'key1', 'value1', 'tag1'
      end
      bin(notes, []).stdout.should_not include 'tag1'
    end

    it 'aligns the notes such that values line up' do
      notes = CommandLineNotes.new do |cln|
        cln.note 'k',   'value1'
        cln.note 'key', 'value2'
      end
      spacing1, spacing2, *other_spacing = bin(notes, []).stdout.scan(/ +/)
      other_spacing.should == []
      spacing1.size.should == spacing2.size + 2
    end

    def no_ansi(string)
      string.gsub(/\e\[.*?m/, '')
    end

    it 'prints notes whose value has multiple lines on multiple lines (aligned)' do
      notes = CommandLineNotes.new do |cln|
        cln.note 'k',   'value1'
        cln.note 'key', <<-VALUE
          value2.1  # should be at same indentation as value1
           value2.2 # should be 1 space deeper than value 2.1
        VALUE
      end
      line1, line2, line3, *other_lines = no_ansi(bin(notes, []).stdout).scan(/^.*?v/)
      other_lines.should == []
      line1.size.should == line2.size
      line3.size.should == line2.size + 1
    end

    it 'prints every other line coloured' do
      notes = CommandLineNotes.new do |cln|
        cln.note 'key1', 'value1'
        cln.note 'key2', 'value2'
        cln.note 'key3', "value3.1\nalue3.2"
      end
      line1, line2, line3, line4, *rest = bin(notes, []).stdout.each_line.to_a
      rest.should == []
      line1.should start_with CommandLineNotes::Color1
      line2.should start_with CommandLineNotes::Color2
      line3.should start_with CommandLineNotes::Color1
      line4.should_not start_with CommandLineNotes::Color2 # b/c it's part of note3
      line4.should end_with CommandLineNotes::NoColor
    end
  end
else
  words = CommandLineNotes.new do |words|
    words.description = "A list of words I like and don't want to forget"

    words.note "abate"             , "(of something perceived as hostile, threatening, or negative) become less intense or widespread"
    words.note "acquisitive"       , "excessively interested in acquiring money or material things."
    words.note "adage"             , "a proverb or short statement expressing a general truth" , "aphorism", "adage", "maxim", "proverb", "platitude", "fable", "epigram"
    words.note "adjudicate"        , "make a formal judgment or decision about a problem or disputed matter: the committee adjudicates on all betting disputes"
    words.note "anhedonia"         , "inability to feel pleasure"
    words.note "ape"               , "imitate the behavior or manner of (someone or something), esp. in an absurd or unthinking way"
    words.note "aphorism"          , "a pithy observation that contains a general truth, such as, \"if it ain't broke, don't fix it.\"" , "aphorism", "adage", "maxim", "proverb", "platitude", "fable", "epigram"
    words.note "aporia"            , "an irresolvable internal contradiction or logical disjunction in a text, argument, or theory"
    words.note "apotheosis"        , <<-DEFINITION
      the highest point in the development of something; culmination or climax
      the elevation of someone to divine status; deification.
    DEFINITION
    words.note "archetype"         , "a very typical example of a certain person or thing, an original that has been imitated"
    words.note "ardent"            , "enthusiastic or passionate"
    words.note "argot"             , "the jargon or slang of a particular group or class: teenage argot." , "argot", "vernacular", "lexicon"
    words.note "artifice"          , "clever or cunning devices or expedients, especially as used to trick or deceive others"
    words.note "atavistic"         , "relating to or characterized by reversion to something ancient or ancestral"
    words.note "banal"             , "so lacking in originality as to be obvious and boring"
    words.note "balkanize"         , "divide (a region or body) into smaller mutually hostile states or groups."
    words.note "benight"           , "envelop with social, intellectual, or moral darkness"
    words.note "brigand"           , "a member of a gang that ambushes and robs people in forests and mountains."
    words.note "buttonhole"        , "to detain in conversation by or as if by holding on to the outer garments of" , "I'm sorry I'm late. I was buttonholed by a coworker just as I was leaving my office."
    words.note "burgeoning"        , "begin to grow or increase rapidly; flourish: manufacturers are keen to cash in on the burgeoning demand."
    words.note "cad"               , "a man who behaves dishonorably, esp. toward a woman"
    words.note "canard"            , "an unfounded rumor or story: the old canard that LA is a cultural wasteland."
    words.note "catechism"         , "a series of fixed questions, answers, or precepts used for instruction in other situations."
    words.note "circumspect"       , "wary and unwilling to take risks"
    words.note "coalesce"          , "come together and form one mass or whole"
    words.note "collate"           , <<-DEFINITION
      collect and combine (texts, information, or sets of figures) in proper order.
      compare and analyze (texts or other data): these accounts he collated with his own experience.
    DEFINITION
    words.note "confluence"        , "an act or process of merging: a major confluence of the world's financial markets."
    words.note "consanguinity"     , "relating to or denoting people descended from the same ancestor: consanguineous marriages"
    words.note "consonance"        , <<-DEFINITION
      * Generally:  agreement or compatibility between opinions or actions.
      * In prosody: the recurrence of similar sounds (especially consonants) in close proximity.
      * In music:   the combination of notes that are in harmony with each other due to the relationship between their frequencies.
    DEFINITION
    words.note "contrarian"        , "a person who opposes or rejects popular opinion, esp. in stock exchange dealing."
    words.note "coquette"          , "a woman who flirts."
    words.note "crib"              , "informal copy (another person's work) illicitly or without acknowledgment"
    words.note "culpable"          , "deserving blame"
    words.note "demagogue"         , "a political leader who seeks support by appealing to popular desires and prejudices rather than by using rational argument"
    words.note "dilettante"        , "a person who cultivates an area of interest, such as the arts, without real commitment or knowledge"
    words.note "disparage"         , "regard or represent as being of little worth"
    words.note "enervation"        , "a feeling of being drained of energy or vitality"
    words.note "ennui"             , "a feeling of listlessness and dissatisfaction arising from a lack of occupation or excitement."
    words.note "epigram"           , "a pithy saying or remark expressing an idea in a clever and amusing way.aphorism" , "adage", "maxim", "proverb", "platitude", "fable", "epigram"
    words.note "epitome"           , "(the epitome of) a person or thing that is a perfect example of a particular quality or type"
    words.note "equanimity"        , "mental calmness, composure, and evenness of temper, esp. in a difficult situation: she accepted both the good and the bad"
    words.note "erudite"           , "having or showing great knowledge or learning"
    words.note "ethos"             , "the characteristic spirit of a culture, era, or community as manifested in its beliefs and aspirations"
    words.note "etiology"          , "the investigation or attribution of the cause or reason for something, often expressed in terms of historical or mythical explanation."
    words.note "exculpate"         , "show or declare that (someone) is not guilty of wrongdoing"
    words.note "expiate"           , "atone for (guilt or sin)"
    words.note "explanatory gap"   , "the difficulty that physicalist theories of mind have in explaining how physical properties give rise to the way things feel when they are experienced"
    words.note "fable"             , "a short story, typically with animals as characters, conveying a moral." , "aphorism", "adage", "maxim", "proverb", "platitude", "fable", "epigram"
    words.note "frenetic"          , "fast and energetic in a rather wild and uncontrolled way"
    words.note "gaslighting"       , "manipulate (someone) by psychological means into questioning their own sanity"
    words.note "gerrymander"       , "manipulate the boundaries of (an electoral constituency) so as to favor one party or class."
    words.note "gerontology"       , "the study of the social, psychological, cognitive, and biological aspects of aging."
    words.note "gestalt"           , "Psychology - an organized whole that is perceived as more than the sum of its parts."
    words.note "haptic"            , "of or relating to the sense of touch, in particular relating to the perception and manipulation of objects using the senses of touch and proprioception."
    words.note "hegemony"          , "leadership or dominance, especially by one country or social group over others"
    words.note "humbug"            , "deceptive or false talk or behavior"
    words.note "iconoclast"        , "a person who attacks cherished beliefs or institutions."
    words.note "ideation"          , "the formation of ideas or concepts"
    words.note "ignominy"          , "public shame or disgrace"
    words.note "illusory correlation", "phenomenon of perceiving a relationship between variables even when no such relationship exists (https://en.wikipedia.org/wiki/Illusory_correlation)"
    words.note "impasto"           , "the process or technique of laying on paint or pigment thickly so that it stands out from a surface."
    words.note "impetus"           , "the force that makes something happen or happen more quickly"
    words.note "incensed"          , "very angry; enraged: I was absolutely incensed."
    words.note "indexical"         , "deictic: relating to or denoting a word or expression whose meaning is dependent on the context in which it is used, e.g., here, you, me, that one there, or next Tuesday. "
    words.note "inimitable"        , "so good or unusual as to be impossible to copy; unique"
    words.note "intransigent"      , "unwilling or refusing to change one's views or to agree about something."
    words.note "interlocutor"      , "a person who takes part in a dialogue or conversation."
    words.note "intromission"      , "the action or process of inserting the penis into the vagina in sexual intercourse"
    words.note "inundated"         , "overwhelm (someone) with things or people to be dealt with"
    words.note "lascivious"        , "feeling or revealing an overt and often offensive sexual desire"
    words.note "leviathan"         , "(in biblical use) a sea monster, identified in different passages with the whale and the crocodile (e.g., Job 41, Ps. 74:14), and with the Devil (after Isa. 27:1)."
    words.note "lexicon"           , "the vocabulary of a person, language, or branch of knowledge"
    words.note "lifspeki"          , "to show who you are to yourself and to the world through your actions, “You Have Exactly One Life in Which to Do Everything You’ll Ever Do. Act Accordingly” (http://www.saltartists.com/the-most-dangerous-words/)"
    words.note "machination"       , "a scheming or crafty action or artful design intended to accomplish some usually evil end"
    words.note "magnanimously"     , "very generous or forgiving, esp. toward a rival or someone less powerful than oneself."
    words.note "malapropism"       , "the mistaken use of a word in place of a similar-sounding one, often with unintentionally amusing effect, as in, for example, “dance a flamingo” (instead of flamenco)."
    words.note "maudlin"           , "self-pityingly or tearfully sentimental, often through drunkenness"
    words.note "maxim"             , "a short, pithy statement expressing a general truth or rule of conduct" , "aphorism", "adage", "maxim", "proverb", "platitude", "fable", "epigram"
    words.note "meliorative"       , "to make better, opposite of pejorative"
    words.note "mendacious"        , "not telling the truth; lying: mendacious propaganda."
    words.note "misgiving"         , "a feeling of doubt or apprehension about the outcome or consequences of something"
    words.note "monomania"         , "exaggerated or obsessive enthusiasm for or preoccupation with one thing"
    words.note "moratorium"        , "a temporary prohibition of an activity"
    words.note "mudita"            , "sympathetic or unselfish joy, or joy in the good fortune of others. In Buddhism, mudita is significant as one of the Four Immeasurables -- https://twitter.com/austinkleon/status/662288435823022080"
    words.note "myasthenia"        , "a condition causing abnormal weakness of certain muscles"
    words.note "natty"             , "(esp. of a person or an article of clothing) smart and fashionable"
    words.note "ostentatious"      , "characterized by vulgar or pretentious display; designed to impress or attract notice"
    words.note "palpable"          , "able to be touched or felt, (esp. of a feeling or atmosphere) so intense as to be almost touched or felt: a palpable sense of loss."
    words.note "perennial"         , "lasting or existing for a long or apparently infinite time; enduring or continually recurring; apparently permanently engaged in a specified role or way of life"
    words.note "perfidy"           , "deceitfulness; untrustworthiness."
    words.note "performativity"    , "(my defn) speech which determines the identity of a person -- ie the language defines who the person is, rather than who they are dictating their language"
    words.note "petulant"          , "childishly sulky or bad-tempered"
    words.note "platitude"         , "a remark or statement, esp. one with a moral content, that has been used too often to be interesting or thoughtful" , "aphorism", "adage", "maxim", "proverb", "platitude", "fable", "epigram"
    words.note "polymathy"         , "a person of wide-ranging knowledge or learning."
    words.note "precipice"         , "a very steep rock face or cliff, sometimes figurative: the country was teetering on the precipice of political anarchy."
    words.note "precipice"         , "a very steep rock face or cliff, typically a tall one"
    words.note "precocious"        , "indicative of early development"
    words.note "prescient"         , "having or showing knowledge of events before they take place: a prescient warning."
    words.note "proclivity"        , "a tendency to choose or do something regularly; an inclination or predisposition toward a particular thing"
    words.note "procrustean"       , "(especially of a framework or system) enforcing uniformity or conformity without regard to natural variation or individuality"
    words.note "propensity"        , "an inclination or natural tendency to behave in a particular way: a propensity for violence"
    words.note "proverb"           , "a short pithy saying in general use, stating a general truth or piece of advice." , "aphorism", "adage", "maxim", "proverb", "platitude", "fable", "epigram"
    words.note "punitive"          , "inflicting or intended as punishment"
    words.note "qualia"            , "the internal and subjective component of sense perceptions, arising from stimulation of the senses by phenomena."
    words.note "querulously"       , "complaining in a petulant or whining manner"
    words.note "quintessential"    , "representing the most perfect or typical example of a quality or class"
    words.note "quixotic"          , "exceedingly idealistic; unrealistic and impractical"
    words.note 'quorum sensing'    , 'A system of stimuli and response correlated to population density. Many species of bacteria use quorum sensing to coordinate gene expression according to the density of their local population.'
    words.note "razzing"           , "tease (someone) playfully"
    words.note "reconcile"         , "restore friendly relations between, cause to coexist in harmony, make (one account) consistent with another, settle (a disagreement), (reconcile someone to) make someone accept (a disagreeable or unwelcome thing)"
    words.note "relegate"          , "consign or dismiss to an inferior rank or position"
    words.note "remonstrate"       , "make a forcefully reproachful protest"
    words.note "reprobate"         , <<-DEFINITION
      an unprincipled person (often used humorously or affectionately).
      Christian Theology, archaic (esp. in Calvinism) a sinner who is not of the elect and is predestined to damnation.
    DEFINITION
    words.note "repudiate"         , "refuse to accept or be associated with"
    words.note "requisition"       , "the appropriation of goods, esp. for military or public use"
    words.note "ribald"            , "referring to sexual matters in an amusingly rude or irreverent way"
    words.note "sardonic"          , "grimly mocking or cynical"
    words.note "semiosis"          , "the conversion of objective signals into conventional signs / the process of signification in language or literature."
    words.note "sequester"         , "isolate or hide away (someone or something)"
    words.note "scalawag"          , "a person who behaves badly but in an amusingly mischievous rather than harmful way"
    words.note "schadenfreude"     , <<-DEFINITION
      Schadenfreude is pleasure derived from the misfortunes of others.
      This word is taken from German and literally means "harm-joy".
      It is the feeling of joy or pleasure when one sees another fail or suffer misfortune.
    DEFINITION
    words.note "simulacrum"        , "an unsatisfactory imitation or substitute: a bland simulacrum of American soul music"
    words.note "stricture"         , <<-DEFINITION
      1. a restriction on a person or activity
      2. a sternly critical or censorious remark or instruction
    DEFINITION
    words.note "superlative"       , "expressing the highest or a very high degree of a quality"
    words.note "synthesize"        , "combine (a number of things) into a coherent whole"
    words.note "tabula rasa"       , "an absence of preconceived ideas or predetermined goals; a clean slate: the team did not have complete freedom and a tabula rasa from which to work.", "alpha go"
    words.note "taciturn"          , "reserved or uncommunicative in speech; saying little."
    words.note "teleological"      , "the explanation of phenomena by the purpose they serve rather than by postulated causes."
    words.note "temerity"          , "excessive confidence or boldness; audacity"
    words.note "trepidation"       , "a feeling of fear or agitation about something that may happen: the men set off in fear and trepidation."
    words.note "triage"            , "the process of determining the most important people or things from amongst a large number that require attention."
    words.note "trope"             , "a significant or recurrent theme; a motif"
    words.note "truculence"        , "eager or quick to argue or fight; aggressively defiant"
    words.note "umbrage"           , "offense or annoyance"
    words.note "urbane"            , "(of a person, esp. a man) suave, courteous, and refined in manner."
    words.note "vagabond"          , "a person who wanders from place to place without a home or job"
    words.note "valetudinarian"    , "a person who is unduly anxious about their health."
    words.note "vernacular"        , "the terminology used by people belonging to a specified group or engaging in a specialized activity" , "argot", "vernacular", "lexicon"
    words.note "vet"               , "make a careful and critical examination of"
    words.note "vicissitudes"      , "a change of circumstances or fortune, typically one that is unwelcome or unpleasant"
    words.note "synchrony"         , "simultaneous action, development, or occurrence."
    words.note "copious"           , "abundant in supply or quantity: she took copious notes."
    words.note "beaucoup"          , "many or much"
    words.note "vocaiton"          , "a strong feeling of suitability for a particular career or occupation"
    words.note "extemporaneous"    , "spoken or done without preparation"
    words.note "convalescing"      , "recover one's health and strength over a period of time after an illness or operation: he spent eight months convalescing after the stroke."
    words.note "peremptory"        , "(especially of a person's manner or actions) insisting on immediate attention or obedience, especially in a brusquely imperious way: “Just do it!” came the peremptory reply."
  end
  puts CommandLineNotes::Binary.new(words, ARGV).stdout
end

